//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Openvidu.Net.Aspnet")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyDescriptionAttribute(@"this package generally can help to make webhook endpoint to receive OpenVidu WebHook events quickly and simple, this package can be scaled up to handle many webhook events and manage requests very fast because we use an event bus on memory. this package support after 2.23.0 version of OpenVidu.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.3")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.3")]
[assembly: System.Reflection.AssemblyProductAttribute("Openvidu.Net.Aspnet")]
[assembly: System.Reflection.AssemblyTitleAttribute("Openvidu.Net.Aspnet")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.3")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://gitlab.com/atreya-co/vendor/openvidu/openvidu.net")]

// Generated by the MSBuild WriteCodeFragment class.

